
  




CREATE TABLE D_MOB_DATA_FIX_111118 COMPRESS NOLOGGING AS
Select /*+ PARALLEL(BASE, 16) */ base.X_ATTR_13,base.MOB_GSM_SERVICE_STATUS,MOB_PRO.PROMOTION_GROUP_LVL1,base.PRODUCT_NAME,base.BILLING_ACCOUNT_KEY,trunc (base.exeCUTION_LAUNCH_DT) exeCUTION_LAUNCH_DT,base.WAVE_ID WAVE_ID,base.CAMPAIGN_ID CAMPAIGN_ID,
Case when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','') = 'UNL' then 'SIMO_HIGH'

        when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','')) < 2 then 'SIMO_LOW'

       when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','')) >= 2 and to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB',''))< 10 then 'SIMO_MED'

       when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','')) >= 10 then '%%SIMO_HIGH'

    when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND PROMOTION_GROUP_LVL1 like  '%Handset%' then 'Handset'

    when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND PROMOTION_GROUP_LVL1 = 'Multi SIM only' then 'Multi SIM only'
    else X_ATTR_13 end as PROM_GROUP_PREV
FROM EDW_LOAD_STAGE.NEW_COLOSSUS_SNAP111118 BASE  
LEFT JOIN DM_OWNER_STR_DL.DM_PROMOTION MOB_PRO
ON BASE.MOB_PROMOTION_KEY = MOB_PRO.EDW_PRODUCT_KEY
AND MOB_PRO.PROMOTION_PRODUCT_LINE = '%BT Mob%';


CREATE TABLE D_MOB_DATA_FIX_301218 COMPRESS NOLOGGING AS
Select /*+ PARALLEL(BASE, 16) */ base.X_ATTR_13,base.MOB_GSM_SERVICE_STATUS,MOB_PRO.PROMOTION_GROUP_LVL1,base.PRODUCT_NAME,base.BILLING_ACCOUNT_KEY,trunc (base.exeCUTION_LAUNCH_DT) exeCUTION_LAUNCH_DT,base.WAVE_ID WAVE_ID,base.CAMPAIGN_ID CAMPAIGN_ID,
Case when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','') = 'UNL' then 'SIMO_HIGH'

        when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','')) < 2 then 'SIMO_LOW'

       when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','')) >= 2 and to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB',''))< 10 then 'SIMO_MED'

       when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','')) >= 10 then 'SIMO_HIGH'

    when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND PROMOTION_GROUP_LVL1 like  '%Handset%' then 'Handset'

    when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND PROMOTION_GROUP_LVL1 = 'Multi SIM only' then 'Multi SIM only'
    else X_ATTR_13 end as PROM_GROUP_PREV
FROM EDW_LOAD_STAGE.NEW_ALL_COLOSSUS_SNAP301218 BASE  
LEFT JOIN DM_OWNER_STR_DL.DM_PROMOTION MOB_PRO
ON BASE.MOB_PROMOTION_KEY = MOB_PRO.EDW_PRODUCT_KEY
AND MOB_PRO.PROMOTION_PRODUCT_LINE like '%BT Mob%';


CREATE TABLE D_MOB_DATA_FIX_0231218 COMPRESS NOLOGGING AS
Select /*+ PARALLEL(BASE, 16) */ base.X_ATTR_13,base.MOB_GSM_SERVICE_STATUS,MOB_PRO.PROMOTION_GROUP_LVL1,base.PRODUCT_NAME,base.BILLING_ACCOUNT_KEY,trunc (base.exeCUTION_LAUNCH_DT) exeCUTION_LAUNCH_DT,base.WAVE_ID WAVE_ID,base.CAMPAIGN_ID CAMPAIGN_ID,
Case when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','') = 'UNL' then 'SIMO_HIGH'

        when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','')) < 2 then 'SIMO_LOW'

       when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','')) >= 2 and to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB',''))< 10 then 'SIMO_MED'

       when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','')) >= 10 then 'SIMO_HIGH'

    when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND PROMOTION_GROUP_LVL1 like '%Handset%' then 'Handset'

    when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND PROMOTION_GROUP_LVL1 = 'Multi SIM only' then 'Multi SIM only'
    else X_ATTR_13 end as PROM_GROUP_PREV
FROM EDW_LOAD_STAGE.ALL_COLOSSUS_SNAP231218 BASE  
LEFT JOIN DM_OWNER_STR_DL.DM_PROMOTION MOB_PRO
ON BASE.MOB_PROMOTION_KEY = MOB_PRO.EDW_PRODUCT_KEY
AND MOB_PRO.PROMOTION_PRODUCT_LINE like '%BT Mob%';




CREATE TABLE D_MOB_DATA_FIX_041118 COMPRESS NOLOGGING AS
Select /*+ PARALLEL(BASE, 16) */ base.X_ATTR_13,base.MOB_GSM_SERVICE_STATUS,MOB_PRO.PROMOTION_GROUP_LVL1,base.PRODUCT_NAME,base.BILLING_ACCOUNT_KEY,trunc (base.exeCUTION_LAUNCH_DT) exeCUTION_LAUNCH_DT,base.WAVE_ID WAVE_ID,base.CAMPAIGN_ID CAMPAIGN_ID,
Case when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','') = 'UNL' then 'SIMO_HIGH'

        when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','')) < 2 then 'SIMO_LOW'

       when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','')) >= 2 and to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB',''))< 10 then 'SIMO_MED'

       when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','')) >= 10 then 'SIMO_HIGH'

    when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND PROMOTION_GROUP_LVL1 like '%Handset%' then 'Handset'

    when NVL(X_ATTR_13, 'NONE') = 'NONE' , BASE.MOB_GSM_SERVICE_STATUS = 'L' AND PROMOTION_GROUP_LVL1 = 'Multi SIM only' then 'Multi SIM only'
    else X_ATTR_13 end as PROM_GROUP_PREV
FROM EDW_LOAD_STAGE.ALL_COLOSSUS_SNAP041118 BASE  
LEFT JOIN DM_OWNER_STR_DL.DM_PROMOTION MOB_PRO
ON BASE.MOB_PROMOTION_KEY = MOB_PRO.EDW_PRODUCT_KEY
AND MOB_PRO.PROMOTION_PRODUCT_LINE like '%BT Mob%';


CREATE TABLE D_MOB_DATA_FIX_181118 COMPRESS NOLOGGING AS
Select /*+ PARALLEL(BASE, 16) */ base.X_ATTR_13,base.MOB_GSM_SERVICE_STATUS,MOB_PRO.PROMOTION_GROUP_LVL1,base.PRODUCT_NAME,base.BILLING_ACCOUNT_KEY,trunc (base.exeCUTION_LAUNCH_DT) exeCUTION_LAUNCH_DT,base.WAVE_ID WAVE_ID,base.CAMPAIGN_ID CAMPAIGN_ID,
Case when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','') = 'UNL' then 'SIMO_HIGH'

        when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','')) < 2 then 'SIMO_LOW'

       when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','')) >= 2 and to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB',''))< 10 then 'SIMO_MED'

       when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','')) >= 10 then 'SIMO_HIGH'

    when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND PROMOTION_GROUP_LVL1 like  '%Handset%' then 'Handset'

    when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND PROMOTION_GROUP_LVL1 = 'Multi SIM only' then 'Multi SIM only'
    else X_ATTR_13 end as PROM_GROUP_PREV
FROM EDW_LOAD_STAGE.NEW_COLOSSUS_SNAP181118 BASE  
LEFT JOIN DM_OWNER_STR_DL.DM_PROMOTION MOB_PRO
ON BASE.MOB_PROMOTION_KEY = MOB_PRO.EDW_PRODUCT_KEY
AND MOB_PRO.PROMOTION_PRODUCT_LINE like '%BT Mob%';


  

  






CREATE TABLE D_MOB_DATA_FIX_211018 COMPRESS NOLOGGING AS
Select /*+ PARALLEL(BASE, 16) */ base.X_ATTR_13,base.MOB_GSM_SERVICE_STATUS,MOB_PRO.PROMOTION_GROUP_LVL1,base.PRODUCT_NAME,base.BILLING_ACCOUNT_KEY,trunc (base.exeCUTION_LAUNCH_DT) exeCUTION_LAUNCH_DT,base.WAVE_ID WAVE_ID,base.CAMPAIGN_ID CAMPAIGN_ID,
Case when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','') = 'UNL' then 'SIMO_HIGH'

        when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','')) < 2 then 'SIMO_LOW'

       when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','')) >= 2 and to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB',''))< 10 then 'SIMO_MED'

       when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','')) >= 10 then 'SIMO_HIGH'

    when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND PROMOTION_GROUP_LVL1 like  '%Handset%' then 'Handset'

    when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND PROMOTION_GROUP_LVL1 = 'Multi SIM only' then 'Multi SIM only'
    else X_ATTR_13 end as PROM_GROUP_PREV
FROM EDW_LOAD_STAGE.ALL_COLOSSUS_SNAP211018 BASE  
LEFT JOIN DM_OWNER_STR_DL.DM_PROMOTION MOB_PRO
ON BASE.MOB_PROMOTION_KEY = MOB_PRO.EDW_PRODUCT_KEY
AND MOB_PRO.PROMOTION_PRODUCT_LINE like '%BT Mob%';


CREATE TABLE D_MOB_DATA_FIX_141018 COMPRESS NOLOGGING AS
Select /*+ PARALLEL(BASE, 16) */ base.X_ATTR_13,base.MOB_GSM_SERVICE_STATUS,MOB_PRO.PROMOTION_GROUP_LVL1,base.PRODUCT_NAME,base.BILLING_ACCOUNT_KEY,trunc (base.exeCUTION_LAUNCH_DT) exeCUTION_LAUNCH_DT,base.WAVE_ID WAVE_ID,base.CAMPAIGN_ID CAMPAIGN_ID,
Case when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','') = 'UNL' then 'SIMO_HIGH'

        when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','')) < 2 then 'SIMO_LOW'

       when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','')) >= 2 and to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB',''))< 10 then 'SIMO_MED'

       when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','')) >= 10 then 'SIMO_HIGH'

    when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND PROMOTION_GROUP_LVL1 like  '%Handset%' then 'Handset'

    when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND PROMOTION_GROUP_LVL1 = 'Multi SIM only' then 'Multi SIM only'
    else X_ATTR_13 end as PROM_GROUP_PREV
FROM EDW_LOAD_STAGE.ALL_COLOSSUS_SNAP141018 BASE  
LEFT JOIN DM_OWNER_STR_DL.DM_PROMOTION MOB_PRO
ON BASE.MOB_PROMOTION_KEY = MOB_PRO.EDW_PRODUCT_KEY
AND MOB_PRO.PROMOTION_PRODUCT_LINE like '%BT Mob%';


CREATE TABLE D_MOB_DATA_FIX_281018 COMPRESS NOLOGGING AS
Select /*+ PARALLEL(BASE, 16) */ base.X_ATTR_13,base.MOB_GSM_SERVICE_STATUS,MOB_PRO.PROMOTION_GROUP_LVL1,base.PRODUCT_NAME,base.BILLING_ACCOUNT_KEY,trunc (base.exeCUTION_LAUNCH_DT) exeCUTION_LAUNCH_DT,base.WAVE_ID WAVE_ID,base.CAMPAIGN_ID CAMPAIGN_ID,
Case when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','') = 'UNL' then 'SIMO_HIGH'

        when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','')) < 2 then 'SIMO_LOW'

       when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','')) >= 2 and to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB',''))< 10 then 'SIMO_MED'

       when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','')) >= 10 then 'SIMO_HIGH'

    when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND PROMOTION_GROUP_LVL1 like '%Handset%' then 'Handset'

    when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND PROMOTION_GROUP_LVL1 = 'Multi SIM only' then 'Multi SIM only'
    else X_ATTR_13 end as PROM_GROUP_PREV
FROM EDW_LOAD_STAGE.NEW_COLOSSUS_SNAP281018 BASE  
LEFT JOIN DM_OWNER_STR_DL.DM_PROMOTION MOB_PRO
ON BASE.MOB_PROMOTION_KEY = MOB_PRO.EDW_PRODUCT_KEY
AND MOB_PRO.PROMOTION_PRODUCT_LINE like '%BT Mob%';




CREATE TABLE D_MOB_DATA_FIX_071018 COMPRESS NOLOGGING AS
Select /*+ PARALLEL(BASE, 16) */ base.X_ATTR_13,base.MOB_GSM_SERVICE_STATUS,MOB_PRO.PROMOTION_GROUP_LVL1,base.PRODUCT_NAME,base.BILLING_ACCOUNT_KEY,trunc (base.exeCUTION_LAUNCH_DT) exeCUTION_LAUNCH_DT,base.WAVE_ID WAVE_ID,base.CAMPAIGN_ID CAMPAIGN_ID,
Case when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','') = 'UNL' then 'SIMO_HIGH'

        when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','')) < 2 then 'SIMO_LOW'

       when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','')) >= 2 and to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB',''))< 10 then 'SIMO_MED'

       when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','')) >= 10 then 'SIMO_HIGH'

    when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND PROMOTION_GROUP_LVL1 like '%Handset%' then 'Handset'

    when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND PROMOTION_GROUP_LVL1 = 'Multi SIM only' then 'Multi SIM only'
    else X_ATTR_13 end as PROM_GROUP_PREV
FROM EDW_LOAD_STAGE.NEW_COLOSSUS_SNAP071018 BASE  
LEFT JOIN DM_OWNER_STR_DL.DM_PROMOTION MOB_PRO
ON BASE.MOB_PROMOTION_KEY = MOB_PRO.EDW_PRODUCT_KEY
AND MOB_PRO.PROMOTION_PRODUCT_LINE like '%BT Mob%';


CREATE TABLE D_MOB_DATA_FIX_020918 COMPRESS NOLOGGING AS
Select /*+ PARALLEL(BASE, 16) */ base.X_ATTR_13,base.MOB_GSM_SERVICE_STATUS,MOB_PRO.PROMOTION_GROUP_LVL1,base.PRODUCT_NAME,base.BILLING_ACCOUNT_KEY,trunc (base.exeCUTION_LAUNCH_DT) exeCUTION_LAUNCH_DT,base.WAVE_ID WAVE_ID,base.CAMPAIGN_ID CAMPAIGN_ID,
Case when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','') = 'UNL' then 'SIMO_HIGH'

        when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','')) < 2 then 'SIMO_LOW'

       when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','')) >= 2 and to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB',''))< 10 then 'SIMO_MED'

       when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND MOB_PRO.PROMOTION_GROUP_LVL1 = 'SIM Only' 
    AND to_number(replace(replace(PROMOTION_GROUP_LVL4,'D-',''),'GB','')) >= 10 then 'SIMO_HIGH'

    when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND PROMOTION_GROUP_LVL1 like  '%Handset%' then 'Handset'

    when NVL(X_ATTR_13, 'NONE') = 'NONE' AND BASE.MOB_GSM_SERVICE_STATUS = 'L' AND PROMOTION_GROUP_LVL1 = 'Multi SIM only' then 'Multi SIM only'
    else X_ATTR_13 end as PROM_GROUP_PREV
FROM EDW_LOAD_STAGE.NEW_COLOSSUS_SNAP020918 BASE  
LEFT JOIN DM_OWNER_STR_DL.DM_PROMOTION MOB_PRO
ON BASE.MOB_PROMOTION_KEY = MOB_PRO.EDW_PRODUCT_KEY
AND MOB_PRO.PROMOTION_PRODUCT_LINE like '%BT Mob%';


